### ISSUE TITLE
No checks are being ran Eclipse 2020-12 (4.18.0)

### ISSUE THREAD

**Issue by ToxicMushroom** [fsc4j/fsc4j#27]
#### Info
I mistakenly updated eclipse to 2021 and then realized fsc4j did not support this version (Before 2021 my eclipse + fsc4j worked well). I then uninstalled this new version of eclipse and installed 2020-12 (4.18.0) again.
#### The problem
Now none of the pre/post conditions are being checked.
I made sure the -ea flag is present and used the example from the readme in this repo.

I tried to trigger the pre conditions using the following client code.
https://gist.github.com/ToxicMushroom/e12d6f7da43e083dc627301faa8410f2

**Comment by ToxicMushroom** [comment]
The following looks to relate to this issue:

On MacOS 11.3.1 and Windows 10 I get the same error as @wannestas with the latest version of Eclipse. If I install an older version of Eclipse it installs, but the checker doesn't work. It doesn't check any of the docs written (even with the -ea as VM argument).

_Originally posted by @TIboStans in https://github.com/fsc4j/fsc4j/issues/26#issuecomment-850980993_

**Comment by btj** [comment]
Can you please confirm that FSC4J is installed? If you look in Help -> About Eclipse -> Installation Details -> Installed Software, the version number of Eclipse Java Development Tools should end with `fsc4j-0_5_0`.

**Comment by ToxicMushroom** [comment]
The version number didn't match:
`Eclipse Java Development Tools	3.18.600.v20201202-1800	org.eclipse.jdt.feature.group	Eclipse.org`
Strange since I remember going through the install process step by step at least a couple times.

It is working now after removing sfc4j via the `Install New Software -> Manage` menu and then following the installation steps again.

**Comment by btj** [comment]
Thanks for the update. Presumably, installation failed but without a clear failure message. If you care, you can check your Error log (Window -> Show view -> Error log) to see if it mentions a problem during installation. I am closing this issue for now, but if you have more details that could be actionable, please reopen.

**Comment by ToxicMushroom** [comment]
No errors related to fsc4j were in the error log.
