### ISSUE TITLE
GameCharacter class from Readme: error with old(getHealth)

### ISSUE THREAD

**Issue by Natithan** [fsc4j/fsc4j#3]
The example 'GameCharacter' class gives me the following error: The type Runnable from the descriptor computed for the target context is not visible here.
The error dissappears when I comment out this line in the formal specification: | getHealth() == old(getHealth()) - amount (see image).
I guess this is because the 'old' function is not supported in some way?
![image](https://user-images.githubusercontent.com/17345374/74724298-5a04c980-523c-11ea-9f33-8963e652b426.png)
![image](https://user-images.githubusercontent.com/17345374/74724331-65f08b80-523c-11ea-9a5a-cc393f2a9f10.png)

**Comment by btj** [comment]
This happens when the project has a `module-info.java` file.
